### ISSUE TITLE
validate HTTP response with JSONSchema

### ISSUE THREAD

**Issue by jaypipes** [jaypipes/gdt#1]
Allow specifying an expected JSON response using a referenced JSONSchema.

```yaml
tests:
  - GET: /books
    response:
      json:
        schema: schemas/get_books.json
```

where the user could define a JSONSchema document in `${testdir}/schemas/get_books.json` and that schema would be loaded and used to verify the returned HTTP response body.
