### ISSUE TITLE
support loading request body data from file

### ISSUE THREAD

**Issue by jaypipes** [jaypipes/gdt#15]
For large request bodies, it might be nice to separate the request body into a JSON or YAML file and allow the `gdt.http` file parser to load that file into the request body.

Something like this might work:

```yaml
require:
 - books_api
tests:
 - name: create a new book
   POST: /books
   data_from: data/create_book._request.yaml
   response:
     status: 201
```

with `data/create_book_request.yaml`:

```yaml
title: For Whom The Bell Tolls
published_on: 1940-10-21
pages: 480
author_id: $.authors.by_name["Ernest Hemingway"].id
publisher_id: $.publishers.by_name["Charles Scribner's Sons"].id
```

Clearly, the file would need to be loaded before processing any JSONPath values that might be referenced in the file.

This would make the construction of variants of testing easier (for, say, small variations in a REST API's accepted payload over time, driven by an Accept HTTP header).
