### ISSUE TITLE
Allow HTTP headers to be specified in the request body

### ISSUE THREAD

**Issue by jaypipes** [jaypipes/gdt#16]
Allow for HTTP headers to be specified in the request body for `gdt.http` test files:

```yaml
require:
 - books_api
tests:
 - name: bad accept type sent
   POST: /books
   headers:
       accept: invalid-format-x
   response:
     status: 400
```
