### ISSUE TITLE
Support referencing fixture state from tests

### ISSUE THREAD

**Issue by jaypipes** [jaypipes/gdt#3]
From the rootdir's README, the `create_then_get.yaml` example gdt test file looks like this:

```yaml
require:
 - books_api
 - authors_by_name
 - publishers_by_name
tests:
 - name: create a new book
   POST: /books
   data:
     title: For Whom The Bell Tolls
     published_on: 1940-10-21
     pages: 480
     author_id: $authors_by_name['Ernest Hemingway']['ID']
     publisher_id: $publishers_by_name["Charles Scribner's Sons"]['ID']
   response:
     status: 201
     headers:
      - Location
 - name: look up that created book
   GET: $LOCATION
   response:
     status: 200
     json:
       paths:
         $.author.name: Ernest Hemingway
         $.publisher.address.state: New York
       path_formats:
         $.id: uuid4
```

The lines:

```yaml
     author_id: $authors_by_name['Ernest Hemingway']['ID']
     publisher_id: $publishers_by_name["Charles Scribner's Sons"]['ID']
```

reference the "authors_by_name" and "publishers_by_name" fixtures defined in the `require:` top-level object.

However, this functionality does not yet work. The README was aspirational and needs to match reality.
